# Build settings
#gems:
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-jupyter-notebook

#theme: metaphor

# Site settings
title: "Correlated Noise"
description: > # this means to ignore newlines until "email:"
   Coin Flips, Covariances, and Common Sense in Baseball

email: marcoviero@protonmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/Tigers.jpg"

name: 'Marco Viero'
author: 'marco viero'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://wrapgenius.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@wrapgenius'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-72857061-3

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/wrapgenius
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url: https://www.github.com/wrapgenius
    desc:	Fork me on github
    share_url: https://www.github.com/wrapgenius
    share_title:
    share_link:

#  - icon: linkedin
#    url:	https://linkedin.com/
#    desc:	Add me on Linkedin
#    share_url:
#    share_title:
#    share_link:
